# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, project_id: int=None):  # noqa: E501
        """ProjectId - a model defined in Swagger

        :param project_id: The project_id of this ProjectId.  # noqa: E501
        :type project_id: int
        """
        self.swagger_types = {
            'project_id': int
        }

        self.attribute_map = {
            'project_id': 'project_id'
        }

        self._project_id = project_id

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The project_id of this ProjectId.  # noqa: E501
        :rtype: ProjectId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def project_id(self) -> int:
        """Gets the project_id of this ProjectId.

        ID  # noqa: E501

        :return: The project_id of this ProjectId.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: int):
        """Sets the project_id of this ProjectId.

        ID  # noqa: E501

        :param project_id: The project_id of this ProjectId.
        :type project_id: int
        """

        self._project_id = project_id
